# Project information
site_name: PHOTONAI - Graph
repo_name: 'photonai-graph'
repo_url: 'https://github.com/wwu-mmll/photonai-graph'
site_dir: '../docs'
edit_uri: 'edit/master/documentation/docs'


# Social media
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/wwu_mmll'

# Theme configuration
theme: 
  name: 'material'
  palette:
    primary: 'teal'
    accent: 'teal'
  font: false
  logo: assets/img/photonai-01.png
  favicon: assets/img/photonai-02.png
  features:
     - toc.integrate

# Latex
extra_javascript:
  - assets/javascript/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# extensions
markdown_extensions:
  - pymdownx.arithmatex:
        generic: true
  - pymdownx.highlight:
      auto_title: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - codehilite
  - admonition
  - pymdownx.details

# Site structure
nav: 
- Home: 'index.md'
- Installation: 'installation.md'
- Getting Started: 'getting_started.md'
- PHOTONAI Graph Workflow: 'workflow.md'
- Extending PHOTONAI Graph: 'extending_photonai_graph.md'
- API:
  - API Introduction: 'api/introduction.md'
  - Graph Construction: 'api/graph_construction.md'
  - Graph Conversions: 'api/graph_conversions.md'
  - Population Averaging: 'api/population_averaging.md'
  - Dynamic Utilities: 'api/dynamic_utils.md'
  - Graph Measures: 'api/graph_measures.md'
  - Graph Embeddings: 'api/graph_embeddings.md'
  - Graph Kernels: 'api/graph_kernels.md'
  - Graph Neural Networks: 'api/graph_convnets.md'
  - Graph Utilities: 'api/graph_utilities.md'
  - Graph Controllability: 'api/graph_controllability.md'
- Examples:
    - Networkx Loading: 'examples/networkx_pipeline.ipynb'
    - Graph Embeddings:
      - Graph Embedding LEM: 'examples/GraphEmbedding_lem_example.ipynb'
      - Graph Embedding LLE: 'examples/GraphEmbedding_lle_example.ipynb'
    - Graph Neural Networks:
        - GNN Classification: 'examples/GraphNN_classification_example.ipynb'
        - GNN Regression: 'examples/GraphNN_regression_example.ipynb'
    - Graph Kernels:
        - PyramidMatch: 'examples/GraphKernel_PyramidMatch_example.ipynb'
        - SVMtheta: 'examples/GraphKernel_SVMtheta_example.ipynb'
    - Graph Measures:
        - Extraction Example: 'examples/GraphMeasure_extraction_example.ipynb'
        - Pipeline Example: 'examples/GraphMeasure_pipeline_example.ipynb'
    - Graph Litmus Test: 'examples/GraphLitmusTest.ipynb'

extra_css:
  - assets/stylesheets/material.css
  - assets/stylesheets/fonts.css

plugins:
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: numpy
          rendering:
            show_source: false
  - mkdocs-jupyter:
      execute: True
