# Project information
site_name: PHOTONAI - Graph
repo_name: 'photonai-graph'
repo_url: 'https://github.com/wwu-mmll/photonai-graph'
site_dir: '../docs'


# Social media
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/medicalmachinelearninglab'

# Theme configuration
theme: 
  name: 'material'
  palette:
    primary: 'deep orange'
    accent: 'deep orange'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# Latex
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

# extensions
markdown_extensions:
  - pymdownx.arithmatex
  - codehilite
  - admonition

# Site structure
nav: 
- Home: 'index.md'
- Installation: 'installation.md'
- Getting Started: 'getting_started.md'
- Workflow: 'workflow.md'
- API: 'API.md'
- Graph Construction: 
    - Theory: 
       'graph_construction.md'
    - Examples:
       'examples/graph_construction_examples.md'
- Graph Measures: 'graph_measures.md'
- Graph Embeddings: 'graph_embeddings.md'
- Graph Neural Networks: 'graph_convnets.md'
- Graph Utilities: 'graph_utilities.md'

extra_css:
  - stylesheets/material.css

plugins:
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: numpy
          rendering:
            show_source: false