# Project information
site_name: PHOTONAI - Graph
repo_name: 'photonai-graph'
repo_url: 'https://github.com/wwu-mmll/photonai-graph'
site_dir: '../docs'
edit_uri: 'edit/master/documentation/docs'


# Social media
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/medicalmachinelearninglab'

# Theme configuration
theme: 
  name: 'material'
  palette:
    primary: 'teal'
    accent: 'teal'
  font:
    text: 'Roboto'
    code: 'Space Mono'
  logo: assets/img/favicon.ico
  favicon: assets/img/favicon.ico

# Latex
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

# extensions
markdown_extensions:
  - pymdownx.highlight:
      auto_title: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - codehilite
  - admonition
  - pymdownx.details

# Site structure
nav: 
- Home: 'index.md'
- Installation: 'installation.md'
- Getting Started: 'getting_started.md'
- PHOTONAI Graph Workflow: 'workflow.md'
- Load and Save Graphs: 'load_and_save.md'
- Extending PHOTONAI Graph: 'extending_photonai_graph.md'
- API:
  - API Introduction: 'api/introduction.md'
  - Graph Construction:
      - Functions:
         'api/graph_construction.md'
      - Examples:
         'api/examples/graph_construction_examples.md'
  - Graph Conversions: 'api/graph_conversions.md'
  - Population Averaging: 'api/population_averaging.md'
  - Dynamic Utilities: 'api/dynamic_utils.md'
  - Graph Measures: 'api/graph_measures.md'
  - Graph Embeddings: 'api/graph_embeddings.md'
  - Graph Kernels: 'api/graph_kernels.md'
  - Graph Neural Networks: 'api/graph_convnets.md'
  - Graph Utilities: 'api/graph_utilities.md'

extra_css:
  - assets/stylesheets/material.css

plugins:
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: numpy
          rendering:
            show_source: false