name: Update documentation
on: push

jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.8'

      - name: Install mkdocs requirements
        run: pip install mkdocs mkdocs-material pymdown-extensions mkdocstrings-python mkdocs-jupyter jupyter

      - name: Install photonai_graph requirements
        run: pip install -r requirements.txt

      - name: Install photonai_graph
        run: pip install .

      - name: Build docs
        run: |
          cd documentation
          PYTHONPATH=.. mkdocs build
